Repository WritelyForWriters/FE, pull requests merged in 2025-03, with the labels that each got.

#53 Feat: [공통 컴포넌트] 액션바 UI 퍼블리싱
  package-lock.json
  package.json
  src/app/components/action-bar/ActionBar.module.scss
  src/app/components/action-bar/ActionBar.tsx
  src/app/components/dropdown/Dropdown.tsx
  src/app/components/switch/EditModeSwitch.module.scss
  src/app/components/switch/EditModeSwitch.tsx
  src/app/constants/workspace/keyboardShortcuts.ts
  src/app/planner/[id]/components/planner-action-bar/PlannerActionBar.tsx
  src/app/planner/[id]/layout.tsx
  src/app/planner/[id]/page.tsx
  src/app/styles/style.scss
  src/app/workspace/[id]/components/workspace-action-bar/KeyboardShortcutsHelper.tsx
  src/app/workspace/[id]/components/workspace-action-bar/WorkspaceActionBar.tsx
  src/app/workspace/[id]/page.tsx
Labels: ✍️ 작업 공간

#71 KAN-32 Feat: 작업 공간 및 작품 플래너 페이지 레이아웃 구현
  src/app/(after-login)/planner/[id]/_components/planner-action-bar/PlannerActionBar.tsx
  src/app/(after-login)/planner/[id]/page.module.scss
  src/app/(after-login)/planner/[id]/page.tsx
  src/app/(after-login)/workspace/[id]/_components/memo-pannel/MemoItem.module.scss
  src/app/(after-login)/workspace/[id]/_components/memo-pannel/MemoItem.tsx
  src/app/(after-login)/workspace/[id]/_components/memo-pannel/MemoPannel.module.scss
  src/app/(after-login)/workspace/[id]/_components/memo-pannel/MemoPannel.tsx
  src/app/(after-login)/workspace/[id]/_components/planner-pannel/PlannerItem.module.scss
  src/app/(after-login)/workspace/[id]/_components/planner-pannel/PlannerItem.tsx
  src/app/(after-login)/workspace/[id]/_components/planner-pannel/PlannerPannel.module.scss
  src/app/(after-login)/workspace/[id]/_components/planner-pannel/PlannerPannel.tsx
  src/app/(after-login)/workspace/[id]/_components/workspace-action-bar/KeyboardShortcutsHelper.tsx
  src/app/(after-login)/workspace/[id]/_components/workspace-action-bar/WorkspaceActionBar.tsx
  src/app/(after-login)/workspace/[id]/page.module.scss
  src/app/(after-login)/workspace/[id]/page.tsx
  src/app/components/action-bar/ActionBar.module.scss
  src/app/components/editor/DefaultEditor.module.scss
  src/app/components/editor/DefaultEditor.tsx
  src/app/components/pannel/IndexPannel.module.scss
  src/app/components/pannel/IndexPannel.tsx
  src/app/components/pannel/Pannel.module.scss
  src/app/components/pannel/Pannel.tsx
  src/app/components/tab/Tab.module.scss
  src/app/page.tsx
  src/app/planner/[id]/layout.tsx
  src/app/planner/[id]/page.tsx
  src/app/types/common/editor.ts
  src/app/workspace/[id]/layout.tsx
  src/app/workspace/[id]/page.tsx
Labels: 🎨 design

#73 UI: 로그인 페이지 퍼블리싱
  src/app/(before-login)/login/page.module.scss
  src/app/(before-login)/login/page.tsx
  src/app/components/buttons/OutLinedButton.module.scss
  src/app/components/buttons/OutLinedButton.tsx
  src/app/components/buttons/TextButton.module.scss
  src/app/components/text-field/TextField.module.scss
  src/app/components/text-field/TextField.tsx
  src/app/components/text-field/TextFieldInput.tsx
Labels: 🎨 design

#74 UI: 회원가입 페이지 퍼블리싱
  src/app/(before-login)/signup/page.module.scss
  src/app/(before-login)/signup/page.tsx
  src/app/components/checkbox-group/CheckboxGroup.tsx
  src/app/components/checkbox/Checkbox.module.scss
  src/app/components/checkbox/Checkbox.tsx
  src/app/constants/signup/message.ts
  src/app/constants/signup/pattern.ts
  src/app/styles/_typography.scss
Labels: 🎨 design

#76 UI: 비밀번호 찾기 페이지 퍼블리싱
  src/app/(before-login)/find-password/page.module.scss
  src/app/(before-login)/find-password/page.tsx
Labels: 🎨 design

#77 UI: 비밀번호 변경 페이지 퍼블리싱
  src/app/(before-login)/reset-password/[token]/page.module.scss
  src/app/(before-login)/reset-password/[token]/page.tsx
  src/app/components/text-field/TextField.tsx
Labels: 🎨 design

#78 KAN-120 Feat: 내 서재 페이지 UI 및 기능 구현
  src/app/(after-login)/(bookself)/_components/CardItem.module.scss
  src/app/(after-login)/(bookself)/_components/CardItem.tsx
  src/app/(after-login)/(bookself)/_components/Dashboard.module.scss
  src/app/(after-login)/(bookself)/_components/Dashboard.tsx
  src/app/(after-login)/(bookself)/_components/MainHeader.module.scss
  src/app/(after-login)/(bookself)/_components/MainHeader.tsx
  src/app/constants/bookself/number.ts
  src/app/constants/common/toastMessage.ts
  src/app/page.tsx
  src/app/services/members/members.ts
  src/app/services/products/products.ts
  src/app/types/common/apiResponse.ts
  src/app/types/members/index.ts
  src/app/types/members/membersDto.ts
  src/app/types/products/index.ts
  src/app/types/products/productsDto.ts
  src/app/utils/formatDate.ts
  src/app/utils/index.ts
Labels: ✨feat, 🎨 design
