Repository WritelyForWriters/FE, pull requests merged in 2025-02, with the labels that each got.

#55 Design/시스템 디자인에 맞춰 글로벌 스타일 적용
  public/fonts/PretendardVariable.woff2
  src/app/globals.css
  src/app/styles/_variables.scss
  src/app/styles/style.scss
Labels: ✨feat

#56 Feat: [작업 공간] TipTap Editor Toolbar 기능 구현
  .prettierrc
  package-lock.json
  package.json
  public/file.svg
  public/globe.svg
  public/icons/ai-option1.svg
  public/icons/ai-option2.svg
  public/icons/ai-option3.svg
  public/icons/ai-option4.svg
  public/icons/indent.svg
  public/icons/outdent.svg
  public/icons/text-align-center.svg
  public/icons/text-align-left.svg
  public/icons/text-align-right.svg
  public/next.svg
  public/vercel.svg
  public/window.svg
  src/app/components/editor/DefaultEditor.module.scss
  src/app/components/editor/DefaultEditor.tsx
  src/app/components/editor/Toolbar.module.scss
  src/app/components/editor/Toolbar.tsx
  src/app/components/select-menu/SelectMenu.module.scss
  src/app/components/select-menu/SelectMenu.tsx
  src/app/extensions/Blockquote.ts
  src/app/extensions/Indent.ts
  src/app/favicon.ico
  src/app/hooks/common/useDetectClose.ts
  src/app/hooks/extensions/useIndent.ts
  src/app/hooks/extensions/useTextAlign.ts
  src/app/hooks/extensions/useTextFormat.ts
  src/app/hooks/extensions/useTextMark.ts
  src/app/hooks/index.ts
  src/app/layout.tsx
  src/app/page.module.css
  src/app/page.tsx
  src/app/styles/style.scss
  src/app/types/common/selectMenu.ts
  src/app/types/index.ts
  tsconfig.json
Labels: ✨feat, ✍️ 작업 공간

#58 Feat: [공통 컴포넌트] 버튼
  src/app/components/buttons/FillButton.module.scss
  src/app/components/buttons/FillButton.tsx
  src/app/components/buttons/TextButton.module.scss
  src/app/components/buttons/TextButton.tsx
  src/app/types/common/button.ts
Labels: ✨feat

#59 Feat: [공통 컴포넌트] 모달
  src/app/components/buttons/FillButton.module.scss
  src/app/components/buttons/TextButton.module.scss
  src/app/components/modal/Modal.module.scss
  src/app/components/modal/Modal.tsx
  src/app/components/modal/Portal.tsx
  src/app/layout.tsx
Labels: ✨feat

#64 Feat: [공통 컴포넌트] Dropdown 생성
  package-lock.json
  package.json
  src/app/components/buttons/FillButton.module.scss
  src/app/components/buttons/TextButton.module.scss
  src/app/components/dropdown/Dropdown.module.scss
  src/app/components/dropdown/Dropdown.tsx
  src/app/components/modal/Modal.module.scss
  src/app/components/modal/Modal.tsx
  src/app/styles/_mixins.scss
Labels: ✨feat, 🎨 design
