Repository WritelyForWriters/FE, pull requests merged in 2025-06, with the labels that each got.

#106 Fix: [QA] Favicon 스타일 수정
  src/app/(after-login)/workspace/[id]/page.module.scss
  src/app/(after-login)/workspace/[id]/page.tsx
  src/app/components/chatbot-chat-input/ChatbotChatInput.tsx
  src/app/components/chatbot-floating-favicon/ChatbotFloatingFavicon.tsx
  src/app/components/chatbot-window/ChatbotWindow.tsx
  src/app/store/faviconRelativePositionAtom.ts
  src/app/store/newChatMessagesAtom.ts
Labels: bug

#108 Fix: [QA] 예고 없는 로그아웃 및 내 서재 관련 이슈 해결
  src/app/(after-login)/(bookself)/_components/CardList.tsx
  src/app/(after-login)/(bookself)/_components/Dashboard.module.scss
  src/app/(after-login)/(bookself)/_components/Dashboard.tsx
  src/app/(after-login)/(bookself)/_components/MainHeader.module.scss
  src/app/(after-login)/(bookself)/_components/MainHeader.tsx
  src/app/(after-login)/layout.tsx
  src/app/api/auth/Auth.ts
  src/app/api/core/AuthInstance.ts
  src/app/components/auth-interceptor/AuthInterceptor.tsx
  src/app/components/tokenRefresher/TokenRefresher.tsx
  src/app/hooks/auth/useLogin.ts
  src/app/hooks/auth/useLogout.ts
  src/app/hooks/products/useProductsQueries.ts
  src/app/hooks/profile/useProfileQueries.ts
  src/app/layout.tsx
  src/app/store/isLoggedInAtom.ts
  src/app/store/isRemberMeAtom.ts
  src/app/types/products/productsResponseType.ts
Labels: bug, ✨feat

#109 Fix: [QA] 작업공간 내 이슈 해결
  src/app/(after-login)/workspace/[id]/_components/planner-pannel/PlannerPannel.tsx
  src/app/(after-login)/workspace/[id]/_components/workspace-action-bar/WorkspaceActionBar.tsx
  src/app/(after-login)/workspace/[id]/page.tsx
  src/app/api/ai-assistant/aiAssistant.ts
  src/app/components/action-bar/ActionBar.module.scss
  src/app/components/auth-interceptor/AuthInterceptor.tsx
  src/app/components/chatbot-assistant-message/ChatbotAssistantMessage.module.scss
  src/app/components/chatbot-chat-input/ChatbotChatInput.tsx
  src/app/components/chatbot-member-message/ChatbotMemberMessage.module.scss
  src/app/components/chatbot-window/ChatbotWindow.tsx
  src/app/components/editor/DefaultEditor.tsx
  src/app/components/pdfExportPreview/PdfExportPreview.tsx
  src/app/components/tokenRefresher/TokenRefresher.tsx
  src/app/constants/common/toastMessage.ts
  src/app/hooks/auth/useRefresh.ts
  src/app/hooks/editor/useTextEditor.tsx
  src/app/hooks/memos/useMemosQueries.ts
  src/app/hooks/products/useProductsQueries.ts
  src/app/hooks/profile/useProfileQueries.ts
  src/app/store/applyProductSettings.ts
  src/app/types/chatbot/chatbot.ts
Labels: bug, ✨feat

#114 [KAN-157] Feat: memo tracking 기능 구현
  src/app/(after-login)/workspace/[id]/_components/memo-pannel/MemoItem.tsx
  src/app/(after-login)/workspace/[id]/_components/memo-pannel/MemoPannel.tsx
  src/app/(after-login)/workspace/[id]/page.tsx
  src/app/api/memos/memos.ts
  src/app/extensions/UnderlineHighlight.ts
  src/app/hooks/editor/useMemos.tsx
  src/app/hooks/editor/useMemosTracking.ts
  src/app/types/memos/memosResponseType.ts
Labels: ✨feat

#120 Feature/kan 161 if2 negative feedback
  src/app/components/auth-interceptor/AuthInterceptor.tsx
  src/app/components/chatbot-assistant-message/ChatbotAssistantMessage.tsx
  src/app/components/negative-feedback-select-menu/NegativeFeedbackSelectMenu.module.scss
  src/app/components/negative-feedback-select-menu/NegativeFeedbackSelectMenu.tsx
  src/app/constants/common/toastMessage.ts
  src/app/hooks/auth/useLogin.ts
Labels: ✨feat
