Repository WritelyForWriters/FE, pull requests merged in 2025-04, with the labels that each got.

#80 API: 비밀번호 변경 기능 구현
  src/app/(before-login)/change-password/complete/not-found.tsx
  src/app/(before-login)/change-password/complete/page.module.scss
  src/app/(before-login)/change-password/complete/page.tsx
  src/app/(before-login)/change-password/services/changePasswordService.ts
  src/app/(before-login)/change-password/types/changePassword.ts
  src/app/(before-login)/find-password/page.tsx
  src/app/(before-login)/find-password/services/findPasswordService.ts
  src/app/components/text-field/TextFieldInput.tsx
  src/app/constants/common/toastMessage.ts
Labels: ✨feat

#75 KAN-103 Feat: planner template ui
  package-lock.json
  package.json
  src/app/(after-login)/planner/[id]/_components/planner-action-bar/PlannerActionBar.tsx
  src/app/(after-login)/planner/[id]/_components/planner-character-form-list/PlannerCharacterFormList.module.scss
  src/app/(after-login)/planner/[id]/_components/planner-character-form-list/PlannerCharacterFormList.tsx
  src/app/(after-login)/planner/[id]/_components/planner-character-form/PlannerCharacterForm.module.scss
  src/app/(after-login)/planner/[id]/_components/planner-character-form/PlannerCharacterForm.tsx
  src/app/(after-login)/planner/[id]/_components/planner-idea-note/PlannerIdeaNote.module.scss
  src/app/(after-login)/planner/[id]/_components/planner-idea-note/PlannerIdeaNote.tsx
  src/app/(after-login)/planner/[id]/_components/planner-plot-form/PlannerPlotForm.module.scss
  src/app/(after-login)/planner/[id]/_components/planner-plot-form/PlannerPlotForm.tsx
  src/app/(after-login)/planner/[id]/_components/planner-synopsis-form-container/PlannerSynopsisFormContainer.module.scss
  src/app/(after-login)/planner/[id]/_components/planner-synopsis-form-container/PlannerSynopsisFormContainer.tsx
  src/app/(after-login)/planner/[id]/_components/planner-synopsis-form/PlannerSynopsisForm.module.scss
  src/app/(after-login)/planner/[id]/_components/planner-synopsis-form/PlannerSynopsisForm.tsx
  src/app/(after-login)/planner/[id]/_components/planner-tabs/PlannerTabs.module.scss
  src/app/(after-login)/planner/[id]/_components/planner-tabs/PlannerTabs.tsx
  src/app/(after-login)/planner/[id]/_components/planner-world-view-form/PlannerWorldViewForm.module.scss
  src/app/(after-login)/planner/[id]/_components/planner-world-view-form/PlannerWorldViewForm.tsx
  src/app/(after-login)/planner/[id]/page.module.scss
  src/app/(after-login)/planner/[id]/page.tsx
  src/app/components/buttons/FillButton.module.scss
  src/app/components/buttons/TextButton.module.scss
  src/app/components/editor/planner-idea-note-editor/PlannerIdeaNoteEditor.module.scss
  src/app/components/editor/planner-idea-note-editor/PlannerIdeaNoteEditor.tsx
  src/app/components/editor/planner-idea-note-editor/PlannerIdeaNoteToolbar.module.scss
  src/app/components/editor/planner-idea-note-editor/PlannerIdeaNoteToolbar.tsx
  src/app/components/form-wrapper/FormWrapper.tsx
  src/app/components/pannel/IndexPannel.module.scss
  src/app/components/pannel/IndexPannel.tsx
  src/app/components/select-menu/SelectMenu.tsx
  src/app/components/text-field/TextField.module.scss
  src/app/components/text-field/TextField.tsx
  src/app/components/text-field/TextFieldLabel.tsx
  src/app/components/text-field/TextFieldTextarea.tsx
  src/app/constants/planner/plannerConstants.ts
  src/app/store/editorAtoms.ts
  src/app/store/plannerAtoms.ts
  src/app/types/planner/plannerSynopsisFormValues.ts
  src/app/types/planner/plannerTab.ts
Labels: ✨feat, 🎨 design

#84 UI: [AI 어시스턴트 인터페이스 2] 메시지 입력창 컴포넌트
  public/icons/expand-circle-down.svg
  public/icons/expand-circle-up.svg
  src/app/components/auto-resizing-textarea/AutoResizingTextarea.tsx
  src/app/components/buttons/OutLinedButton.module.scss
  src/app/components/buttons/OutLinedButton.tsx
  src/app/components/chatbot-chat-input/ChatbotChatInput.module.scss
  src/app/components/chatbot-chat-input/ChatbotChatInput.tsx
  src/app/page.tsx
  src/app/store/chatInputModeAtom.ts
  src/app/store/chatModeAtom.ts
  src/app/store/clickedButtonAtom.ts
  src/app/store/selectedPromptAtom.ts
  src/app/store/selectedRangeAtom.ts
  src/app/types/chatbot/chatbot.ts
Labels: 🎨 design

#86 UI: [AI 어시스턴트 인터페이스 2] 고정 메시지 컴포넌트
  public/icons/arrow-down.svg
  public/icons/arrow-up.svg
  public/icons/pin.svg
  src/app/components/expandable-content-box/ExpandableContentBox.module.scss
  src/app/components/expandable-content-box/ExpandableContentBox.tsx
Labels: 🎨 design

#85 KAN-126 Feat: editor 목차패널 toc(table of contents) 구현
  src/app/(after-login)/workspace/[id]/page.tsx
  src/app/components/editor/DefaultEditor.module.scss
  src/app/components/editor/DefaultEditor.tsx
  src/app/components/pannel/IndexPannel.module.scss
  src/app/components/pannel/IndexPannel.tsx
  src/app/extensions/Heading.ts
  src/app/types/common/pannel.ts
  src/app/utils/addHeadingId.ts
  src/app/utils/getTocFromEditor.ts
  src/app/utils/index.ts
Labels: ✨feat

#88 [KAN-125] Feat: 작품 자동 저장 기능 구현
  src/app/(after-login)/workspace/[id]/_components/workspace-action-bar/WorkspaceActionBar.tsx
  src/app/(after-login)/workspace/[id]/page.tsx
  src/app/components/editor/DefaultEditor.tsx
  src/app/constants/workspace/message.ts
  src/app/constants/workspace/number.ts
  src/app/store/editorAtoms.ts
  src/app/store/productsAtoms.ts
Labels: ✨feat, ✍️ 작업 공간
